# Generated by Django 5.1.3 on 2024-12-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.sourcecategory')),
            ],
            options={
                'verbose_name_plural': 'Source Categories',
            },
        ),
        migrations.CreateModel(
            name='SourceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(default=0)),
                ('relevance_score', models.IntegerField(default=0)),
                ('authority_score', models.IntegerField(default=0)),
                ('freshness_score', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('overall_rank', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('analysis_notes', models.JSONField(default=dict)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketing.contentsource')),
                ('categories', models.ManyToManyField(to='marketing.sourcecategory')),
            ],
            options={
                'verbose_name_plural': 'Source Analyses',
            },
        ),
    ]
