# Generated by Django 5.1.3 on 2024-12-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_oauthstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediacredentials',
            old_name='api_key',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='socialmediacredentials',
            old_name='api_secret',
            new_name='client_secret',
        ),
    ]
