# Generated by Django 5.1.3 on 2024-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_socialmediacredentials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediacredentials',
            name='access_token',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='socialmediacredentials',
            name='access_token_secret',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediacredentials',
            name='client_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='socialmediacredentials',
            name='client_secret',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='socialmediacredentials',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
