# Generated by Django 5.1.3 on 2024-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_socialmediacredentials_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
